Fixed bugs.

diff --git a/patch-o b/patch-o
--- a/patch-o
+++ b/patch-o
@@ -20,10 +20,10 @@ function  CopyAndAttachPatch() {
         local  patchPath="$2"
     fi
     local  folderPath="$( GetFolderRelativePath  "${patchPath}"  "/" )"
-    local  patchYAML="$( ChangePatchToYAML "${patchPath}" )"
+    local  patchYAML="$( ChangePatchToYAML "${patchPath}" )"  #search: patchYAML
     local  oldIFS="$IFS"
     IFS=$'\n'
-    local  pathPairLines=( $( SortPathPairLines "$( FilterPathPairLines "${patchYAML}" )" ) )
+    local  pathPairLines=( $( SortPathPairLines "$( FilterPathPairLines "${patchYAML}" )" ) )  #search: pathPairLines
     IFS="$oldIFS"
     if [ "${option}" == "-f" ]; then
         local  overwritten="${True}"
@@ -142,8 +142,8 @@ function  SortPathPairLines() {
     IFS=$'\n'
     local  infiniteLoopStopper=99
 
-    #// line example in "paths": "base :attached:1"
-    local  paths="$( echo  "${pathPairLines}"  |  sed -E  's/$/1/')"
+    #// line example in "paths": "base :attached: |:1"
+    local  paths="$( echo  "${pathPairLines}"  |  sed -E  's/$/:1/')"
 
     for (( ii = 2; ii < ${infiniteLoopStopper}; ii += 1 )); do
         local  i=$(( ${ii} - 1 ))
@@ -168,13 +168,13 @@ function  SortPathPairLines() {
         Error  "Too many level of dependency between base path and attached path."
     fi
     IFS="$oldIFS"
-    local  maxLevel=$(( ${i} - 1 ))
+    local  maxLevel="${i}"
     sortedPaths=""
     for (( i = 1; i <= ${maxLevel}; i += 1 )); do
-        sortedPaths="$( AppendToNextLine  "${sortedPaths}"  "$( echo "${paths}"  |  grep ':${i}$' )" )"
+        sortedPaths="$( AppendToNextLine  "${sortedPaths}"  "$( echo "${paths}"  |  grep ":${i}\$" )" )"
     done
 
-    echo  echo  "{sortedPaths}"  |  sed -E  's/[0-9]*$//'
+    echo  "${sortedPaths}"  |  sed -E  's/[0-9]*$//'
 }
 
 function  ChangePatchToYAML() {
@@ -218,7 +218,7 @@ function  FilterPathPairLines() {
 
 function  GetBasePath() {
     local  pathPair="$1"  #// "__AttachedPath__ :__BasePath__: |"
-    echo  "${pathPair}"  |  grep -o ':.*:'  |  sed -E  "s/://g"
+    echo  "${pathPair}"  |  grep -o ':[^:]*:'  |  sed -E  "s/://g"
 }
 
 function  GetAttachedPath() {
@@ -269,6 +269,15 @@ function  GetFolderRelativePath() {
         fi
     else
         echo  "${parentPath}${lastSeparatorIfNotCurrent}"
+    fi
+}
+
+function  AppendToNextLine() {
+    if [ "$1" == "" ]; then
+        echo  "$2"
+    else
+        echo  "$1
+$2"
     fi
 }
 
@@ -406,6 +415,49 @@ function  TestAll() {
     TestReverse  "test"  "../patch1"
     TestManually  "y"
     TestManually  "n"
+}
+
+#// pp "$config"
+#// pp "$config" config
+#// pp "$array" array  ${#array[@]}  "${array[@]}"
+#// $( pp "$config" >&2 )
+function  pp() {
+    local  value="$1"
+    local  variableName="$2"
+    if [ "${variableName}" != "" ]; then  variableName=" ${variableName} "  ;fi
+    local  oldIFS="$IFS"
+    IFS=$'\n'
+    local  valueLines=( ${value} )
+    IFS="$oldIFS"
+    if [[ "$(declare -p ${variableName})" =~ "declare -a" ]]; then
+        local  type="array"
+    elif [ "${#valueLines[@]}" == 1  -o  "${#valueLines[@]}" == 0 ]; then
+        local  type="oneLine"
+    else
+        local  type="multiLine"
+    fi
+
+    if [[ "${type}" == "oneLine" ]]; then
+        echo  "@@@${variableName}= \"${value}\" ---------------------------"
+    elif [[ "${type}" == "multiLine" ]]; then
+        echo  "@@@${variableName}---------------------------"
+        echo  "\"${value}\""
+    elif [[ "${type}" == "array" ]]; then
+        echo  "@@@${variableName}---------------------------"
+        local  count="$3"
+        if [ "${count}" == "" ]; then
+            echo  "[0]: \"$4\""
+            echo  "[1]: ERROR: pp parameter is too few"
+        else
+            local  i="0"
+            for (( i = 0; i < ${count}; i += 1 ));do
+                echo  "[$i]: \"$4\""
+                shift
+            done
+        fi
+    else
+        echo  "@@@${variableName}? ---------------------------"
+    fi
 }
 
 True=0
